# Generated by Django 5.2 on 2025-04-23 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='item',
            field=models.CharField(choices=[('burger', '漢堡'), ('pizza', '披薩')], max_length=50),
        ),
    ]
